<?php
ob_start(); //store any output display on browser
/* Using ob_start allows you to keep the content in a server-side buffer until you are ready to display it. This is commonly used to so that pages can send headers 'after' they've 'sent' some content already (ie, deciding to redirect half way through rendering a page) */

/* Output buffering allows you to have output of PHP (primarily generated by echo ) stored into an memory (ie. buffer) instead of immediately transmitted to the browser or terminal. */
/* it creates the buffer (invisible holding cell) that will store all output after it is called. */
//ob_get_clean(); // stores buffer content into variable and turns off buffering.




/* 
ob_get_clean() removes the buffer (without printing it), and returns its content.

ob_get_flush() prints the buffer, removes it, and returns its content.

Both function will terminate the buffer. */

?>
<div>
    <span>text</span>
    <a href="#">link</a>
</div>
<?php
echo ob_get_contents();
echo ob_get_contents();

ob_get_clean();
ob_get_contents();

echo "fdfdffdsfd";


?>
